version: '3'

services:
  goaccess_log_analyzer:
    image: allinurl/goaccess
    container_name: goaccess_log_analyzer
    depends_on:
      - goaccess_log_follower
    ports:
      - "7890:7890"
    volumes:
      - goaccess_report:/srv/report
      - ./goaccess.conf:/srv/data/goaccess.conf
      - goaccess_log:/srv/logs
      - ./goaccess.sh:/home/goaccess.sh
    entrypoint: sh /home/goaccess.sh

  goaccess_nginx:
      image: nginx
      container_name: goaccess_nginx
      depends_on:
        - goaccess_log_analyzer
      volumes:
        - goaccess_report:/usr/share/nginx/html

  goaccess_nginx_auth:
        image: keisato/nginx-basic-auth-proxy
        container_name: goaccess_nginx_auth
        env_file:
          - ./env/basic_auth.env
        environment:
          - BACKEND=goaccess_nginx:80
        links:
          - goaccess_nginx
        ports:
          - "${DASHBOARD_PORT}:80"

  goaccess_log_follower:
      image: kroniak/ssh-client
      container_name: goaccess_log_follower
      env_file:
        - ./env/ssh.env
      volumes:
        - goaccess_log:/home/logs
        - ./log_follower.sh:/home/log_follower.sh
        - ./id_rsa:/root/.ssh/id_rsa
      entrypoint: ash /home/log_follower.sh

volumes:
  goaccess_log:
  goaccess_report: